require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PingPongsController do

  def mock_ping_pong(stubs={})
    @mock_ping_pong ||= mock_model(PingPong, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all ping_pongs as @ping_pongs" do
      PingPong.stub(:all) { [mock_ping_pong] }
      get :index
      assigns(:ping_pongs).should eq([mock_ping_pong])
    end
  end

  describe "GET show" do
    it "assigns the requested ping_pong as @ping_pong" do
      PingPong.stub(:find).with("37") { mock_ping_pong }
      get :show, :id => "37"
      assigns(:ping_pong).should be(mock_ping_pong)
    end
  end

  describe "GET new" do
    it "assigns a new ping_pong as @ping_pong" do
      PingPong.stub(:new) { mock_ping_pong }
      get :new
      assigns(:ping_pong).should be(mock_ping_pong)
    end
  end

  describe "GET edit" do
    it "assigns the requested ping_pong as @ping_pong" do
      PingPong.stub(:find).with("37") { mock_ping_pong }
      get :edit, :id => "37"
      assigns(:ping_pong).should be(mock_ping_pong)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ping_pong as @ping_pong" do
        PingPong.stub(:new).with({'these' => 'params'}) { mock_ping_pong(:save => true) }
        post :create, :ping_pong => {'these' => 'params'}
        assigns(:ping_pong).should be(mock_ping_pong)
      end

      it "redirects to the created ping_pong" do
        PingPong.stub(:new) { mock_ping_pong(:save => true) }
        post :create, :ping_pong => {}
        response.should redirect_to(ping_pong_url(mock_ping_pong))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ping_pong as @ping_pong" do
        PingPong.stub(:new).with({'these' => 'params'}) { mock_ping_pong(:save => false) }
        post :create, :ping_pong => {'these' => 'params'}
        assigns(:ping_pong).should be(mock_ping_pong)
      end

      it "re-renders the 'new' template" do
        PingPong.stub(:new) { mock_ping_pong(:save => false) }
        post :create, :ping_pong => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ping_pong" do
        PingPong.stub(:find).with("37") { mock_ping_pong }
        mock_ping_pong.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ping_pong => {'these' => 'params'}
      end

      it "assigns the requested ping_pong as @ping_pong" do
        PingPong.stub(:find) { mock_ping_pong(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ping_pong).should be(mock_ping_pong)
      end

      it "redirects to the ping_pong" do
        PingPong.stub(:find) { mock_ping_pong(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ping_pong_url(mock_ping_pong))
      end
    end

    describe "with invalid params" do
      it "assigns the ping_pong as @ping_pong" do
        PingPong.stub(:find) { mock_ping_pong(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ping_pong).should be(mock_ping_pong)
      end

      it "re-renders the 'edit' template" do
        PingPong.stub(:find) { mock_ping_pong(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ping_pong" do
      PingPong.stub(:find).with("37") { mock_ping_pong }
      mock_ping_pong.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the ping_pongs list" do
      PingPong.stub(:find) { mock_ping_pong }
      delete :destroy, :id => "1"
      response.should redirect_to(ping_pongs_url)
    end
  end

end
